version: "3"

services:
  #############################
  # Server SSO
  #############################
  jpproject-sso:
    image: "jpproject-sso"
    build:
      context: .
      dockerfile: sso.dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:5001
      CUSTOMCONNSTR_SSOConnection: "Server=mgb-sqlserver-basic.brazilsouth.azurecontainer.io;Database=identityQa;user=identity;password=R8XRtpwRAQS3L2WQ;MultipleActiveResultSets=True"
      ApplicationSettings:EnableExternalProviders: "false" # Because Auth url is http://jpproject-sso (modified by host to point to 127.0.0.1), then Google and Facebook reject it.
      ApplicationSettings:DatabaseType: SqlServer
      ApplicationSettings:DefaultUser: anderson.tomazeto
      ApplicationSettings:DefaultPass: qazwsxedc123
      ApplicationSettings:DefaultEmail: anderson.tomazeto@metodologiagb.com.br
      ApplicationSettings:UserManagementURL: http://localhost:4400
      ApplicationSettings:IS4AdminUi: http://localhost:4300
      ApplicationSettings:ResourceServerURL: http://localhost:5002
      ApplicationSettings:ShowDefaultUserPass: "true"
      CertificateOptions:Type: Temporary

  # #############################
  # # Management API
  # #############################
  jpproject-api:
    image: jpproject-api
    build:
      context: .
      dockerfile: api.dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: http://+
      CUSTOMCONNSTR_SSOConnection: "Server=mgb-sqlserver-basic.brazilsouth.azurecontainer.io;Database=identityQa;user=identity;password=R8XRtpwRAQS3L2WQ;MultipleActiveResultSets=True"
      ApplicationSettings:Authority: "http://jpproject-sso:5001"
      ApplicationSettings:DatabaseType: SqlServer

  #############################
  # User management UI
  #############################
  jpproject-users:
    image: jpproject-users
    build:
      context: .
      dockerfile: users.dockerfile
      args:
        ENVIRONMENT: docker

  #############################
  # Admin UI
  #############################
  jpproject-admin-ui:
    image: bhdebrito/jpproject-admin-ui

  reverse-proxy:
    container_name: jpproject
    build:
      context: .
      dockerfile: nginx.dockerfile
    ports:
      - "5001:5001"
      - "5002:5002"
      - "4400:4400"
      - "4300:4300"
    depends_on:
      - "jpproject-api"
      - "jpproject-users"
      - "jpproject-sso"

networks:
  default:
    driver: bridge
